### ISSUE TITLE
Roadmap to server switching

### ISSUE THREAD

**Issue by regenerativep** [OpenCliqueCraft/splinter-proxy#44]
(Written in the context of #43's version of the project)

Stage 1: Extremely basic server switch
Scenario can be two servers with matching worlds, one player starting in one of the servers. No chunk sharing or entity ownership in this stage. This is probably the bare minimum for server switching.

- [ ] Basic dummy
  1. Start a second dummy connection to other server
  2. Teleport dummy player to primary player's position
  3. Switch player's primary connection to secondary connection.
  4. Close previously-primary-now-dummy connection.
  - [ ] Swap connections in other direction as well
- [ ] Server plugin to listen for teleport command from proxy. Can use plugin channels

Stage 2: Basic server switch with world synchronization
Scenario can be two or more servers all with matching seeds, one player starting in one server.

- [ ] A way for servers to connect to each other (NATs? plugin channels with proxy as router?)
- [ ] Chunk sharing
  - [ ] Find out what other servers are using a chunk
  - [ ] Listen to and mirror changes in other server's instances of the shared chunk

Stage 3: Server switch with world sync and entity sync

- [ ] Entity mirroring
  - [ ] Chunk ownership system (in proxy? in database?)
  - [ ] Find out what other server listens to a chunk
  - [ ] Transfer chunk ownership to another listener when no longer using chunk
  - [ ] Mirror entities in chunk

Stage 4: Server switch
Scenario can be multiple worlds with matching seeds, multiple players in various servers.

- [ ] Mirror primary player in dummy, ex. movements, effects, animations
- [ ] Relay input from non-primary server sources, such the dummy being damaged in the server it's in
- [ ] Transfer player stats and inventory
- [ ] Loading of existing chunks from shared world data (database?)

None of this is set in stone nor a required order nor the best order and it is possible I've missed things. This is just a potential roadmap that can be followed and may function more like a general checklist.
